# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Worker.gov
description: This site covers common workplace concerns and the federal laws that protect you. See how federal laws protect you from common workplace concerns, and learn about how to take action if you believe your rights were violated.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://worker.gov" # the base hostname & protocol for your site
twitter_username: USDOL

# Build settings
markdown: kramdown

collections:
  profiles:
    output: true
  actions:
    output: true
    permalink: /:collection/:path/
  rights:
    output: true
    permalink: /:collection/:path/
  worker-profiles:
    output: true
  concerns:
    output: true
    permalink: /:collection/:path/
  sidebars:
    output: false
  contactinfo:
    output: false
  blurbs:
    output: false
